# HyprBar Configuration File

window:
  anchor: top # top, left, right or bottom
  margin_top: 0
  margin_bottom: 0
  width: 2560 # The width of the window in pixels
  height: 32 # The height of the window in pixels

  left_container:
    hor_spacing: 6
    components:
      - type: label
        markup: '<span foreground="purple">Temp:</span><span foreground="green">89</span>C'
        css_id: "labelLeft"

  center_container:
    hor_spacing: 6
    components:
      - type: label
        markup: '<span foreground="green"> </span><span foreground="yellow">11:16:32</span>'
        css_id: "labelCenter"

  right_container:
    hor_spacing: 6
    components:
      - type: label
        text: "label 1"
        css_id: "label1"
      - type: label
        text: "label2"
        css_id: "label2"
